### ISSUE TITLE
Cost-based optimization - Task #5

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#38]
Think and implement an effective way of measuring the cost of the various IO functions (inserts, deletes etc). 

Measuring run times is an option but it should be added a separate tool and not by altering all the existing methods. You should also create/use a tool that analyzes the runtime as extensively as possible.

**Comment by 0xCoto** [comment]
I've classified [`database.py`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py)'s functions into five categories for easy/convenient navigation (partially for future reference):

## Generic Functions

- [`save()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L48-L54)
- [`_save_locks()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L56-L61)
- [`load()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L63-L76)
- [`drop_db()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L78-L79)

## I/O Functions

- [`_update()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L83-L89)
- [`create_table()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L92-L109)
- [`drop_table()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L112-L131)
- [`table_from_csv()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L134-L160)
- [`table_to_csv()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L163-L172)
- [`table_from_object()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L174-L185)

## Table Functions

- [`cast_column()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L199-L215)
- [`insert()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L217-L243)
- [`update()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L246-L266)
- [`delete()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L268-L290)
- [`select()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L292-L331)
- [`show_table()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L333-L342)
- [`sort()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L344-L360)
- [`inner_join()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L362-L388)
- [`lockX_table()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L390-L401)
- [`unlock_table()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L403-L411)
- [`is_locked()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L413-L433)

## Meta

- [`_update_meta_length()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L441-L455)
- [`_update_meta_locks()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L457-L467)
- [`_update_meta_insert_stack()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L469-L477)
- [`_add_to_insert_stack()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L480-L488)
- [`_get_insert_stack_for_table()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L490-L498)
- [`_update_meta_insert_stack_for_tb()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L500-L507)

## Indexes

- [`create_index()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L511-L533)
- [`_construct_index()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L535-L548)
- [`_has_index()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L551-L557)
- [`_save_index()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L559-L572)
- [`_load_idx()`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py#L574-L583)

The I/O functions group is probably the most meaningful category to classify in terms of time/computational complexity.

To achieve this, a separate script could call miniDB's `database.py` and measure the CPU/wall time* like so:

```python
from database import Database
import time

db = Database('smdb', load=False)

t0 = time.time()
db.create_table('classroom', ['building', 'room_number', 'capacity'], [str,str,int])
print('The create_table() call took: '+str(time.time() - t0))

t0 = time.time()
db.insert('classroom', ['Packard', '101', '500'])
print('The insert() call took: '+str(time.time() - t0))

### Alternatively, a function could be defined to save a few lines of code ###

def measure(command):
    t0 = time.time()
    exec(command)
    return time.time() - t0
```

However, I would approach this in a slightly different manner. Instead of having a separate script (i.e. the user) measure a function's runtime for every call in a "manual" fashion, I would implement this -since it's not a computationally expensive addition- to the I/O functions *within* `database.py`. No, the user would **not** be informed of the runtime for every function by default (since this is generally redundant for most users, especially for small DBs and tables). Instead, [logging](https://docs.python.org/3/library/logging.html) such information with a `INFO` (or `DEBUG`) log level would make usage more modular.

Example usage:

```python
from database import Database
import logging

db.create_table('classroom', ['building', 'room_number', 'capacity'], [str,str,int])
# (No output)

# Change logger level threshold
logging.basicConfig(level=logging.INFO) # (or logging.DEBUG respectively)

db.create_table('classroom', ['building', 'room_number', 'capacity'], [str,str,int])
# create_table() would now return e.g. 'Runtime: X'
```

(On another note, it's definitely a good idea to suppress all the `print`s in `database.py` and replace them with more flexible user-information methods, but I've just submitted a separate issue for that.)

I can push a PR if there are no objections to implementing this in `database.py`.

---

*`time.time()` measures **wall time** and is compatible with both Py2 and 3. For measuring **CPU time** (slightly more accurate for certain big data applications), one may use `time.process_time()` instead (which is only compatible with Py3):

```python
t0 = time.process_time()
db.command(...)
print(time.process_time() - t0)
